services:
  web-statis:
    image: 1wanzscret/uas-static_2388010018:latest
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html # Folder default untuk image php:apache
    restart: always
