# Menggunakan Nginx (server web yang sangat ringan dan cepat khusus untuk web statis)
FROM nginx:alpine

# Menyalin semua file di folder ini ke dalam folder bawaan Nginx
COPY . /usr/share/nginx/html/

# Port standar Nginx
EXPOSE 80
